name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: golang:1.23.3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -o pc

    - name: Run tests
      run: go test ./...

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: pc
        path: ./pc